### ISSUE TITLE
Why do you deploy it separately with Heroku and Github?

### ISSUE THREAD

**Issue by calvin197** [april9288/runninglate#1]
What if a user go to your web site and make an interaction with your backend real fast, will there be any issue because your Heroku server is still sleeping?

**Comment by april9288** [comment]
Hello. Calvin.
Thank you for the code review.
I am currently working on this web app and it's not complete yet.
My plan is to totally refactor with Next.js which is a framework that allows us to do server-side rendering. So It might take a while to resolve that issue.
Thank you again.
